import { Redis } from 'ioredis';
import { Pool } from 'pg';

import type { IdempotencyStorage } from '../../src/interfaces/idempotency-storage.interface';
import { PostgresStorage } from '../../src/storage/postgres.storage';
import { RedisStorage } from '../../src/storage/redis.storage';

export type FailureBackend = 'redis' | 'postgres';
export type CrashPoint = 'before-business-commit' | 'after-business-commit' | 'after-complete';
export type CompleteFailure = 'before-write-rejection' | 'applied-write-rejection';

export interface FailureChildConfig {
  backend: FailureBackend;
  namespace: string;
  rawKey: string;
  crashPoint?: CrashPoint;
  completeFailure?: CompleteFailure;
}

export interface FailureClientResult {
  status: number;
  body?: unknown;
  idempotencyStatus?: string;
  events: string[];
}

/** Names are generated by the fixture, never supplied by an application. */
export function fixtureTables(namespace: string) {
  if (!/^s5_[a-f0-9]+$/.test(namespace)) {
    throw new Error('Invalid failure fixture namespace');
  }
  return {
    records: `${namespace}_records`,
    attempts: `${namespace}_attempts`,
    effects: `${namespace}_effects`,
  };
}

/** Both adapters use an independent PostgreSQL business ledger. */
export async function connectFailureFixture(config: FailureChildConfig) {
  const tables = fixtureTables(config.namespace);
  const pool = new Pool({ connectionString: process.env.TEST_DATABASE_URL });
  const redis =
    config.backend === 'redis'
      ? new Redis(process.env.TEST_REDIS_URL!, { maxRetriesPerRequest: 1 })
      : undefined;
  const storage: IdempotencyStorage = redis
    ? new RedisStorage({ client: redis, keyPrefix: `${config.namespace}:` })
    : new PostgresStorage({ pool, tableName: tables.records });

  return {
    pool,
    redis,
    storage,
    tables,
    async close() {
      if (redis) await redis.quit();
      await pool.end();
    },
  };
}
